### ISSUE TITLE
New colors?

### ISSUE THREAD

**Issue by yigitsr** [Serendipity-Theme/vs-code#18]
Hi. What happened to the old color schema? I've been using Serendipity Dark for a long time and after the latest update it's gone and the new colors came. Is it possible to use the previous colors?

**Comment by Chaphasilor** [comment]
Hey, as you noticed, there was an update in order to improve contrast as well as to make the colors look nicer and be more harmonic. You can install the old version of the theme [from here](https://marketplace.visualstudio.com/items?itemName=wicked-labs.old-serendipity), or by searching for "Old Serendipity" in the VS Code extension pane.

But you should really give the update a try for a few days and see if you really don't like it or just need to get used to it :)

**Comment by yigitsr** [comment]
Thanks for the reply and the link. I've been trying to get used to the new theme and I just can't. I'm so used to the previous one I just installed it again. But I'll give the new one another try. Thank you.

**Comment by michael-andreuzza** [comment]
hey @yigitsr the old theme has always been here.
https://marketplace.visualstudio.com/items?itemName=wicked-labs.old-serendipity
